service: aws-infa-examples
provider:
    name: aws
    runtime: nodejs4.3
    vpc:
         # as of Aug 2016 - these variables must be set in serverless.env.yaml
        securityGroupIds:
            - ${lambdaExecSecurityGroup}
        subnetIds:
            - ${subnetAPrivate}
            - ${subnetBPrivate}
functions:
    hello:
        handler: src/handler.hello
