service: aws-infa-examples
provider:
    name: aws
    runtime: nodejs4.3
    vpc:
        securityGroupIds:
            - ${env:LAMBDA_EXEC_SG}
        subnetIds:
            - ${env:SUBNET_A_PRIVATE}
            - ${env:SUBNET_B_PRIVATE}
functions:
    hello:
        handler: src/handler.hello
